SELECT 
VS.SABOR,
VS.ANO,
VS.TOTAL_DE_VENDAS,
VA.VENDAS_TOTAL_ANO,
CONVERT(VARCHAR(50),ROUND((CONVERT(FLOAT,VS.TOTAL_DE_VENDAS)/ CONVERT(FLOAT,VA.VENDAS_TOTAL_ANO)), 3) * 100) + ' %' AS PERCENTUAL_DE_PARTICIPACAO 
FROM
(
SELECT SB.SABOR, SUM(INF.QUANTIDADE) AS TOTAL_DE_VENDAS, YEAR(NF.DATA_VENDA) as ANO
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON  NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_PRODUTOS SB ON SB.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
WHERE YEAR(NF.DATA_VENDA) = '2015'
GROUP BY SB.SABOR, YEAR(NF.DATA_VENDA)
) VS
INNER JOIN 
(
SELECT YEAR(NF.DATA_VENDA) as ANO
, SUM(INF.QUANTIDADE) AS VENDAS_TOTAL_ANO
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = '2015'
GROUP BY YEAR(NF.DATA_VENDA)
) VA 
ON VA.ANO = VS.ANO

ORDER BY VS.TOTAL_DE_VENDAS DESC